site_name: Technotes
site_url: https://maxstroh.github.io/technotes/
site_description: Tech notes made during work to different topics
site_author: Max Strohbücker

repo_url: https://github.com/MaxStroh/technotes
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    scheme: slate
    primary: orange
    accent: deep orange
  features:
    - content.action.edit
    - content.code.copy
    - content.tabs.link
    - navigation.path
    - navigation.top
    - navigation.tracking
  icon:
    edit: material/pencil

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - md_in_html
  - tables
  - toc:
      permalink: []
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - autorefs
